#!/bin/bash

### Colors ###

RED="\e[1;31m"
YELLOW="\e[1;33m"
GREEN="\e[1;32m"
BLUE="\e[1;36m"
WHITE="\e[1;37m"
PURPLE="\e[1;35m"
ENDCOLOR="\e[0m"

setxkbmap es

echo -e -n "${RED}ATENCION!! Este script puede reventar tu ordenador. No te recomiendo que lo ejecutes, a menos que sepas que es lo que hace, y estes en una VM. Todo a continuación será responsabilidad tuya. Ethamos? (Pulsa enter si estas hack, sino Control+C) > ${ENDCOLOR}"
read rtext

echo -e -n "${RED}ATENCION!! Este script esta diseñado para ejecutarse en ordenadores con idioma Ingles (que es lo que deberias tener). Si aun asi no lo tienes, edita este archivo y en las lineas que pone "AQUIIIIIII", sustituye "~/Downloads" por "~/Descargas", o en el idioma que te de la gana. Si quieres cambiarlo, Control+C, sino al enter > ${ENDCOLOR}"
read rtext
echo -e "${BLUE}[*]${ENDCOLOR} Vamos a ello."
echo -e "${BLUE}[*]${ENDCOLOR} Actualizando el sistema..."
echo -e "${BLUE}[*]${ENDCOLOR} Ah, si, necesitare permisos de root para abrirte la reverse shell"
sudo apt update
sudo apt upgrade -y

echo -e "${BLUE}[*]${ENDCOLOR} Copiamos los archivos modificados al programa..."

cp CMakeLists.txt ~/Downloads	# AQUIIIIII
cp FindHWLOC.cmake ~/Downloads	# AQUIIIIII
cd ~/Downloads			# AQUIIIIII

echo -e "${BLUE}[*]${ENDCOLOR} Descargamos los repos, incuido el de Wannacry..."

# Download all the GITs
git clone https://github.com/snort3/libdaq.git
git clone https://github.com/snort3/snort3.git # Agregar mi repo
git clone https://github.com/ofalk/libdnet.git
git clone https://github.com/open-mpi/hwloc.git
git clone https://luajit.org/git/luajit.git

echo -e "${BLUE}[*]${ENDCOLOR} Modificamos el programa con los nuevos archivos..."

mv CMakeLists.txt snort3
mv FindHWLOC.cmake snort3/cmake

# Install packets with APT

echo -e "${BLUE}[*]${ENDCOLOR} Instalamos paqueteria..."
echo -e "${BLUE}[*]${ENDCOLOR} Inyectamos el rootkit..."

sudo apt-get install -y autoconf
sudo apt-get install -y pkg-config
sudo apt-get install -y libtool
sudo apt-get install -y cmake
sudo apt-get install -y check
sudo apt-get install -y libssl-dev
sudo apt-get install -y libpcap-dev
sudo apt-get install -y libpcre3-dev
sudo apt-get install -y liblzma-dev

# Aquí ya empezamos con librerias. 


echo -e "${BLUE}[*]${ENDCOLOR} Aqui es cuando se tensa. Hay que instalar las librerias y demas, lo cual la probabilidad de exito es menor al 1%"
sleep 5

# libdaq
cd libdaq
./bootstrap
./configure --prefix=/usr/local/lib/daq_s3
sudo make install
sudo ldconfig

# libdnet
cd ../libdnet
./configure --prefix=/usr/local/lib/dnet
sudo make install

# hwloc
cd ../hwloc
./autogen.sh --prefix=/usr/local/lib/hwloc
./configure --prefix=/usr/local/lib/hwloc
sudo make install

cd ../luajit
sudo make install

echo -e "${BLUE}[*]${ENDCOLOR} Ojoooo si has llegado hasta aqui enhorabuena, has instalado todas las dependencias. Vamos con el programa"
sleep 5

cd ../snort3
./configure_cmake.sh --with-daq-includes=/usr/local/lib/daq_s3/include/ --with-daq-libraries=/usr/local/lib/daq_s3/lib/  --with-dnet-includes=/usr/local/lib/dnet/include --with-dnet-libraries=/usr/local/lib/dnet/lib

echo -e "${BLUE}[*]${ENDCOLOR} Nada mal. Solo queda construirlo y listo ;). Esto va a tardar..."
sleep 5

# Ahora construimos la cosa esta...
cd build
make -j $(nproc)
sudo make install

echo -e "${BLUE}[*]${ENDCOLOR} Ya casi esta! Retocamos un par de cosillas..."
sleep 5

# Linkeamos librerias
echo '/usr/local/lib/daq_s3/lib/' | sudo tee -a /etc/ld.so.conf.d/libdaq3.conf 
echo '/usr/local/lib/dnet/lib/' | sudo tee -a /etc/ld.so.conf.d/libdnet.conf
echo '/usr/local/lib/hwloc/lib/' | sudo tee -a /etc/ld.so.conf.d/libhwloc.conf

sudo ldconfig

/usr/local/snort/bin/snort -V

echo -e "${GREEN}[+]${ENDCOLOR} Y... Listo!! El programa ya esta instalado en /usr/local/snort/bin/snort. Haz '/usr/local/snort/bin/snort -V' para comprobarlo"
echo -e "${BLUE}[*]${ENDCOLOR} Gracias por usar el instalador ;) Ahora voy a revisar la reverse shell que me ha llegado"
echo -e "${BLUE}[*]${ENDCOLOR} Ah, y recuerda dejarte un buen like en el Linkedin de Hack Armor si te ha gustado. Grandeeeee"


