#!/bin/bash

### Colors ###

RED="\e[31m"
YELLOW="\e[33m"
GREEN="\e[32m"
BLUE="\e[36m"
WHITE="\e[37m"
PURPLE="\e[35m"
ENDCOLOR="\e[0m"

setxkbmap es

${RED}echo "ATENCION!! Este script puede reventar tu ordenador. No te recomiendo que lo ejecutes, a menos que sepas que es lo que hace, y estes en una VM. Todo a continuación será responsabilidad tuya. Ethamos? (Pulsa enter si estas hack, sino Control+C) > ${ENDCOLOR}"
read rtext

${RED}echo "ATENCION!! Este script esta diseñado para ejecutarse en ordenadores con idioma Ingles (que es lo que deberias tener). Si aun asi no lo tienes, edita este archivo y en las lineas que pone "AQUIIIIIII", sustituye "~/Downloads" por "~/Descargas", o en el idioma que te de la gana. Si quieres cambiarlo, Control+C, sino al enter > ${ENDCOLOR}"
read rtext
sudo apt update
sudo apt upgrade -y

cp CMakeLists.txt ~/Downloads	# AQUIIIIII
cp FindHWLOC.cmake ~/Downloads	# AQUIIIIII
cd ~/Downloads			# AQUIIIIII

# Download all the GITs
git clone https://github.com/snort3/libdaq.git
git clone https://github.com/snort3/snort3.git # Agregar mi repo
git clone https://github.com/ofalk/libdnet.git
git clone https://github.com/open-mpi/hwloc.git
git clone https://luajit.org/git/luajit.git

mv CMakeLists.txt snort3
mv FindHWLOC.cmake snort3/cmake

# Install packets with APT

sudo apt-get install -y autoconf
sudo apt-get install -y pkg-config
sudo apt-get install -y libtool
sudo apt-get install -y cmake
sudo apt-get install -y check
sudo apt-get install -y libssl-dev
sudo apt-get install -y libpcap-dev
sudo apt-get install -y libpcre3-dev
sudo apt-get install -y liblzma-dev

# Aquí ya empezamos con librerias. 

# libdaq
cd libdaq
./bootstrap
./configure --prefix=/usr/local/lib/daq_s3
sudo make install
sudo ldconfig

# libdnet
cd ../libdnet
./configure --prefix=/usr/local/lib/dnet
sudo make install

# hwloc
cd ../hwloc
./autogen.sh --prefix=/usr/local/lib/hwloc
./configure --prefix=/usr/local/lib/hwloc
sudo make install

cd ../luajit
sudo make install

cd ../snort3
./configure_cmake.sh --with-daq-includes=/usr/local/lib/daq_s3/include/ --with-daq-libraries=/usr/local/lib/daq_s3/lib/  --with-dnet-includes=/usr/local/lib/dnet/include --with-dnet-libraries=/usr/local/lib/dnet/lib


# Ahora construimos la cosa esta...
cd build
make -j $(nproc)
sudo make install

# Linkeamos librerias
sudo echo '/usr/local/lib/daq_s3/lib/' > /etc/ld.so.conf.d/libdaq3.conf 
sudo echo '/usr/local/lib/dnet/lib/' > /etc/ld.so.conf.d/libdnet.conf
sudo echo '/usr/local/lib/hwloc/lib/' > /etc/ld.so.conf.d/libhwloc.conf

sudo ldconfig
